# Generated by Django 4.1.5 on 2023-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
