# Generated by Django 4.1.5 on 2023-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='defult_portions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
